version: '2'
services:
 django:
  build: .
  #image: tiangolo/uwsgi-nginx:python3.6
  volumes:
    - ./:/app
    - './entrypoint.sh:/entrypoint.sh'
  environment:
   #UWSGI_INI: '/app/uwsgi.ini'
   STATIC_URL: '/static'
   ENV STATIC_PATH: '/app/static'
  links:
    - pg-database  
  depends_on:
    - pg-database

  ports:
   - '80:80'
  
 pg-database:
  image: postgres:9.6
  environment:
   POSTGRES_USER: 'postgres'
   POSTGRES_PASSWORD: 'postgres'
   PGDATA: '/var/lib/postgresql/data/pgdata'
   POSTGRES_DB: 'assistant'
   POSTGRES_PORT: '5432'
  volumes:
   - './db:/var/lib/postgresql/data'    
  ports:
   - '25432:5432'
