# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_parse', '0016_auto_20171214_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=256)),
                ('gallery_prop', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery')),
                ('gallery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_parse.eBayItemGallery')),
            ],
        ),
    ]
