# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_prop',
            field=models.TextField(blank=True),
        ),
    ]
