# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_auto_20171214_1507'),
        ('gallery', '0002_auto_20171214_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='species.Species'),
        ),
    ]
