apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    {{- include "my-ebay-assistant.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.nginx.targetPort }}
      targetPort: {{ .Values.nginx.targetPort}}
      protocol: TCP      
  selector:
    app: {{ .Values.nginx.name }}
  type: {{ .Values.nginx.type }}
