apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    {{- include "my-ebay-assistant.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.postgresql.host }}
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
