apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    group: system-service
spec:
  type: {{ .Values.postgtresql.type }}
  externalName: {{ .Values.postgresql.host }}
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
