apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.main.name }}
  labels:
    {{- include "my-ebay-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.main.port }}
      targetPort: {{ .Values.main.port }}
      protocol: TCP
  selector:
    app: {{ .Values.main.name }}
  type: NodePort
