# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
    ]
