# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0002_auto_20171027_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
