# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0003_auto_20171027_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='setting_comment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
