# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0005_auto_20171031_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='ebay_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ebaypaymentmethod',
            name='payment_method_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='listing_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
