# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0007_ebayitem_ebay_gallery_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayitem',
            name='ebay_item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ebayitem',
            name='ebay_item_shipping_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
