# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ebay_parse.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0009_auto_20171101_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='eBayItemGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_image', models.ImageField(upload_to='imgs')),
            ],
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='ebay_item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ebayitem',
            name='ebay_gallery_icon',
            field=models.ImageField(default=ebay_parse.models.load_empty_image, upload_to='icons'),
        ),
        migrations.AddField(
            model_name='ebayitemgallery',
            name='ebay_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_parse.eBayItem'),
        ),
    ]
