# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0010_auto_20171108_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayitemgallery',
            old_name='ebay_item_id',
            new_name='ebay_item',
        ),
    ]
