# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0011_auto_20171108_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaycategory',
            name='ebay_category_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
