# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0012_ebaycategory_ebay_category_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaycategory',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebaycategory',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebaycategory',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebaycategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ebaycategory',
            name='ebay_category_parent',
            field=mptt.fields.TreeForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ebay_parse.eBayCategory'),
        ),
    ]
