# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0013_auto_20171110_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebaycategory',
            old_name='ebay_category_parent',
            new_name='parent',
        ),
    ]
