# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 15:28
from __future__ import unicode_literals

from django.db import migrations
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_parse', '0014_auto_20171110_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='search_index',
            field=djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False),
        ),
    ]
