apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.nginx.name }}
  name: {{ .Values.nginx.name }}
spec:
spec:
  selector:
      matchLabels:
        app: {{ .Values.nginx.name }}
  replicas: {{ .Values.nginx.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.nginx.name }}
        image: nginx
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.nginx.targetPort }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx", "-s", "quit"]
        volumeMounts:
          - mountPath: /static
            name: static
            readOnly: true
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-conf
            subPath: nginx.conf
            readOnly: true
      volumes:
        - name: static
          configMap:
            name: static
        - name: nginx-conf
          configMap:
            name: nginx-conf
      restartPolicy: Always
status: {}
