apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    io.kompose.service: {{ .Values.nginx.name }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  nginx.conf:
        user nginx;
        worker_processes  1;

        pid        /var/run/nginx.pid;
                    error_log /dev/stdout info;

        events {
            worker_connections  1024;
            }

        http {
            include    mime.types;
            log_format main 'ip:$remote_addr htuser:$remote_user now:$time_local[$msec] elapsed:$request_time[up:$upstream_response_time] '
                                  'st:$status bytes:$body_bytes_sent host:$host port:$server_port req:"$request" ref:"$http_referer" '
                                  'ua:"$http_user_agent" xfwd:"$http_x_forwarded_for" upstream:$upstream_addr ';

            server {
                listen 80;
                listen [::]:80;
                access_log /var/log/nginx/access.log main;

                location / {
                    root /static;
                }

                error_page 500 502 503 504 /500.html;
                error_page 404 /404.html;
                error_page 422 /422.html;
                client_max_body_size 10M;
                keepalive_timeout 10;
          }
        }
