# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_parse', '0014_auto_20171110_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=256)),
                ('species_first_name', models.CharField(max_length=128)),
                ('species_last_name', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebay_parse.eBayCategory')),
            ],
        ),
    ]
