# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_scpecies2item'),
    ]

    operations = [
        migrations.CreateModel(
            name='stopWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
            ],
        ),
    ]
