# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_stopwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_photo',
            field=models.ImageField(blank=True, upload_to='species'),
        ),
    ]
