# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_species_species_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='species',
            managers=[
                ('search_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='search_index',
            field=djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False),
        ),
    ]
