# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_auto_20171129_0953'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='species',
            managers=[
            ],
        ),
    ]
